### ISSUE TITLE
Support ESM or add compatibility for ESM packages like nanoid

### ISSUE THREAD

**Issue by kerodkibatu** [fireayehu/chapa-nodejs#12]
I'm encountering an issue while using your package in a project that relies on ECMAScript Modules (ESM). The nanoid package is an ES Module, and it’s being required in chapa-nodejs.cjs.development.js, which uses CommonJS. This results in the following error:

```powershell
Uncaught Error Error [ERR_REQUIRE_ESM]: require() of ES Module C:\PaymentGig\node_modules\nanoid\index.js from C:\PaymentGig\node_modules\chapa-nodejs\dist\chapa-nodejs.cjs.development.js not supported.
Instead change the require of index.js in C:\PaymentGig\node_modules\chapa-nodejs\dist\chapa-nodejs.cjs.development.js to a dynamic import() which is available in all CommonJS modules.
    at Module._extensions..js (internal/modules/cjs/loader:1389:19)
    at Module.load (internal/modules/cjs/loader:1208:32)
    at Module._load (internal/modules/cjs/loader:1024:12)
    at Module.require (internal/modules/cjs/loader:1233:19)
    at require (internal/modules/helpers:179:18)
    at <anonymous> (c:\PaymentGig\node_modules\chapa-nodejs\dist\chapa-nodejs.cjs.development.js:8:14)
    at Module._compile (internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (internal/modules/cjs/loader:1416:10)
    at Module.load (internal/modules/cjs/loader:1208:32)
    at Module._load (internal/modules/cjs/loader:1024:12)
    at Module.require (internal/modules/cjs/loader:1233:19)
    at require (internal/modules/helpers:179:18)
    at <anonymous> (c:\PaymentGig\node_modules\chapa-nodejs\dist\index.js:7:20)
    at Module._compile (internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (internal/modules/cjs/loader:1416:10)
    at Module.load (internal/modules/cjs/loader:1208:32)
    at Module._load (internal/modules/cjs/loader:1024:12)
    at cjsLoader (internal/modules/esm/translators:348:17)
    at <anonymous> (internal/modules/esm/translators:297:7)
    at run (internal/modules/esm/module_job:222:25)
    --- await ---
    at runEntryPointWithESMLoader (internal/modules/run_main:147:19)
    at executeUserEntryPoint (internal/modules/run_main:166:5)
    at <anonymous> (internal/main/run_main_module:28:49)
chapa-nodejs.cjs.development.js:8
```

**Steps to Reproduce:**
1. Use `chapa-nodejs` in a Node.js project set to use ESM
2. Run the code and encounter the error.

**Comment by fireayehu** [comment]
@kerodkibatu The issue has been fixed  in this PR https://github.com/fireayehu/chapa-nodejs/pull/13, let me know if the issue persists anymore

**Comment by kerodkibatu** [comment]
Great, Will do. Thanks
